version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - echo Build started on `date`
      - cd horizons-proj
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn jacoco:report
      - mvn xml:transform
      - echo \"$(cat target/generated-resources/xml/xslt/target/site/jacoco/jacoco.xml)% covered\"
artifacts:
  files:
    - horizons-proj/target/horizons-proj-0.0.1-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes
