version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - cd horizons-proj
      - mvn package -DskipTests
artifacts:
  files:
    - target/horizons-proj-1.0-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes